apply plugin: "java"
apply plugin: "org.wisepersist.gwt"
apply plugin: "war"

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

gwt {
    gwtVersion='2.10.0' // Updated GWT version
    maxHeapSize="1G" // Default 256m is not enough for gwt compiler. GWT is HUNGRY
    minHeapSize="1G"

    src = files(file("src/")) // Needs to be in front of "modules" below.
    modules 'com.nostalgi.game.GdxDefinition'
    devModules 'com.nostalgi.game.GdxDefinitionSuperdev'
}

task dist(dependsOn: [clean, compileGwt]) {
    doLast {
        file("build/dist").mkdirs()
        copy {
            from "build/gwt/out"
            into "build/dist"
        }
        copy {
            from "webapp"
            into "build/dist"
            }
        copy {
            from "war"
            into "build/dist"
        }
    }
}

sourceSets.main.java.srcDirs = [ "src/" ]

eclipse.project {
    name = appName + "-html"
}
